import 'package:flutter/material.dart';

class LightTheme {
  ThemeData lightTheme = ThemeData(
      appBarTheme: const AppBarTheme(),
      brightness: Brightness.light,
      elevatedButtonTheme:
          ElevatedButtonThemeData(style: ElevatedButton.styleFrom()),
      primaryColor: const Color(0xFF2196F3),
      primaryColorDark: const Color(0xFF1976D2),
      primaryColorLight: const Color(0xFFBBDEFB),
      secondaryHeaderColor: const Color(0xFFE3F2FD),
      toggleableActiveColor: const Color(0xFF1E88E5),
      errorColor: const Color(0xFFD32F2F),
      canvasColor: const Color(0xFFD32F2F),
      cardColor: const Color(0xFFFFFFFF),
      scaffoldBackgroundColor: const Color(0xFFFAFAFA),
      bottomAppBarColor: const Color(0xFFFFFFFF),
      dialogBackgroundColor: const Color(0xFFFFFFFF),
      indicatorColor: const Color(0xFF2196F3),
      dividerColor: const Color(0x1F000000),
      disabledColor: const Color(0x61000000),
      hoverColor: const Color(0x0A000000),
      focusColor: const Color(0x1F000000),
      highlightColor: const Color(0x66BCBCBC),
      splashColor: const Color(0x66C8C8C8),
      shadowColor: const Color(0xFF000000),
      hintColor: const Color(0x99000000),
      selectedRowColor: const Color(0xFFF5F5F5),
      unselectedWidgetColor: const Color(0x8A000000),
      colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xFF011B95),
          primaryContainer: Color(0xFFF0EFFF),
          onPrimaryContainer: Color(0xFF000000),
          onPrimary: Color(0xFFFFFFFF),
          secondary: Color(0xFF364DDD),
          onSecondary: Color(0xFFFFFFFF),
          secondaryContainer: Color(0xFFF0EFFF),
          onSecondaryContainer: Color(0xFF000000),
          error: Color(0xFFBA1A1A),
          onError: Color(0xFFFFFFFF),
          background: Color(0xFFDEDEF0),
          onSurfaceVariant: Color(0xFF1B1B21),
          outline: Color(0xFF5E5E64),
          shadow: Color(0xFF000000),
          inverseSurface: Color(0xFF2A2D3F),
          onErrorContainer: Color(0xFF000000),
          surfaceVariant: Color(0xFFD2D3EA),
          errorContainer: Color(0xFFFFEDEA),
          onBackground: Color(0xFF000000),
          surfaceTint: Color(0xFF011B95),
          onInverseSurface: Color(0xFFFFFBFE),
          inversePrimary: Color(0xFFDFE0FF),
          tertiary: Color(0xFF801272),
          surface: Color(0xFFDEDEF0),
          onTertiaryContainer: Color(0xFF000000),
          onTertiary: Color(0xFFFFFFFF),
          tertiaryContainer: Color(0xFFFFECF5),
          onSurface: Color(0xFF000000)));
}
